package com.example.autofillgridlayoutmanagerapplication.displaying_yamb_ticket.filling_yamb_ticket

import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import com.example.autofillgridlayoutmanagerapplication.database.*
import com.example.autofillgridlayoutmanagerapplication.database.entities_and_data_classes.ColumnInYamb
import com.example.autofillgridlayoutmanagerapplication.database.entities_and_data_classes.Cubes
import com.example.autofillgridlayoutmanagerapplication.database.entities_and_data_classes.DataAboutRolledCubes
import com.example.autofillgridlayoutmanagerapplication.database.entities_and_data_classes.GameStat
import com.example.autofillgridlayoutmanagerapplication.displaying_yamb_ticket.recyclerAdapter.ItemInGame
import com.example.autofillgridlayoutmanagerapplication.enums_and_interfaces.IHasObservers
import com.example.autofillgridlayoutmanagerapplication.enums_and_interfaces.IViewModelForDisplayingYambTicket
import io.reactivex.Completable
import io.reactivex.Single
import io.reactivex.android.schedulers.AndroidSchedulers
import io.reactivex.disposables.CompositeDisposable
import io.reactivex.schedulers.Schedulers
import java.text.SimpleDateFormat
import java.util.*



class FillingYambTicketViewModel(val database  :GamesPlayedDatabase) : ViewModel() , IViewModelForDisplayingYambTicket, IHasObservers {


    private val  isPopUpForEnteringValuesEnabled_ : MutableLiveData<Boolean> = MutableLiveData(false)
    val isPopUpForEnteringValuesEnabled : LiveData<Boolean>
        get()= isPopUpForEnteringValuesEnabled_

    private val  areDicesRolledTwice_ : MutableLiveData<Boolean> = MutableLiveData()
    val areDicesRolledTwice : LiveData<Boolean>
        get()= areDicesRolledTwice_

    private val itemsInRecycler_ : MutableLiveData<List<ItemInGame>> = MutableLiveData()
    val itemsInRecycler : LiveData<List<ItemInGame>>
        get() = itemsInRecycler_

    private val finishedGame_ = MutableLiveData<Boolean>(false)
    val  finishGameState : LiveData<Boolean>
        get() = finishedGame_

    private val totalPoints_ = MutableLiveData<Int>()
    val  totalPoints : LiveData<Int>
        get() = totalPoints_

    private val showToastForGameSaved_ = MutableLiveData<Boolean>(false)
    val showToastForGameSaved : LiveData<Boolean>
        get() = showToastForGameSaved_

    private val onClickItemPosition_ : MutableLiveData<Int> = MutableLiveData()
    val onClickItemPosition : LiveData<Int>
        get() = onClickItemPosition_

    var diceRolled = listOf<Int>()
    var aheadCall = false
    private val compositeDisposable = CompositeDisposable()
    private var positioOfLastItemClickedTemp = 0

    init {
        //generateStartingItems()
        generateStartingTestItems()
        setupObserverForDataAboutGame()
    }

    private fun setupObserverForDataAboutGame(){
        compositeDisposable.add(
            database.getDataAboutRolledCubesDao().getData(1)
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(){
                this.areDicesRolledTwice_.value = !it.isRecyclerFrozen
                if(!it.isRecyclerFrozen){
                    aheadCall = it.aheadCall
                    diceRolled = generateDiceRolledWithDataFromDatabase(it.cubes)
                }
            }
        )

    }
    fun saveGame(){
       compositeDisposable.add( Completable.fromAction {

           val calendar = Calendar.getInstance()
           val dateFormat = SimpleDateFormat("MM/dd/yyyy", Locale.ITALY)
           val date = dateFormat.format(calendar.time)
           val totalPoints = ListOfItemsModifier.getTotalPoints(itemsInRecycler_.value!!)

           val currentInsertedGameId =
               database.getGameStatsDao().insertGameStats(GameStat(0, date, totalPoints)) //id is autogenerated
           val mapOfPlayedColumns = ListOfItemsModifier.getMapOfColumnsFromListOfItems(itemsInRecycler_.value!!) //turn list into map of columns

           val listOfObjectsRepresentingColumns = mutableListOf<ColumnInYamb>()
           fillListWithFourObjectsWhoEachRepresentOneColumn(listOfObjectsRepresentingColumns, mapOfPlayedColumns,currentInsertedGameId)
           database.getColumnDao().insertColumns(
                listOfObjectsRepresentingColumns[0],
                listOfObjectsRepresentingColumns[1],
                listOfObjectsRepresentingColumns[2],
                listOfObjectsRepresentingColumns[3],
                listOfObjectsRepresentingColumns[4]
            )
       }.subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(
                {
                    changeIsGameFinishedState()
                    this.generateStartingItems()
                    showToastMessage()
                }
            ){
                throw  it
            }
       )


    }

    fun changeListOfItemsWhenValueInserted(valueOfItemPicked: Int){
        this.itemsInRecycler_.value = ListOfItemsModifier.getModifiedListWhenValueInserted(onClickItemPosition.value!!, valueOfItemPicked,itemsInRecycler_.value!!)
        if(ListOfItemsModifier.isGameFinished(itemsInRecycler_.value!!))
            changeIsGameFinishedState()
        enableButtonForRollingDices()
    }
    fun unFreezeAllItems(){
        if(aheadCall)
            this.itemsInRecycler_.value = ListOfItemsModifier.getAheadCallPressedList(itemsInRecycler_.value!!)
        else
            this.itemsInRecycler_.value = ListOfItemsModifier.getUnfreezedList(itemsInRecycler_.value!!)
    }

    fun resetAllItems(){
        changeIsGameFinishedState()
        generateStartingItems()
    }
    fun changePositionOfLastItemClicked(){
        onClickItemPosition_.value = positioOfLastItemClickedTemp
    }
    private fun showToastMessage(){
        this.showToastForGameSaved_.value = true
        this.showToastForGameSaved_.value = false
    }
    private fun fillListWithFourObjectsWhoEachRepresentOneColumn(listOfObjectsRepresentingColumns : MutableList<ColumnInYamb>,mapOfPlayedColumns : Map<Int,List<Int?>>,currentInsertedGameId : Long){
        for((key,rowList) in mapOfPlayedColumns){
            listOfObjectsRepresentingColumns.add(key,
                ColumnInYamb(
                    columnId = 0,
                    correspondingGameId = currentInsertedGameId,
                    one = rowList[0],
                    two = rowList[1],
                    three = rowList[2],
                    four = rowList[3],
                    five = rowList[4],
                    six = rowList[5],
                    sum_form_one_to_six = rowList[6],
                    max = rowList[7],
                    min = rowList[8],
                    max_min = rowList[9],
                    two_pairs = rowList[10],
                    straight = rowList[11],
                    full = rowList[12],
                    poker = rowList[13],
                    yamb = rowList[14],
                    sum_from_two_pairs_to_yamb = rowList[15]
                )
            )
        }
    }
    private fun changeIsGameFinishedState(){
        finishedGame_.value =  !finishedGame_.value!!
    }

    fun changeTotalPoints(){
        this.totalPoints_.value = ListOfItemsModifier.getTotalPoints(itemsInRecycler_.value!!)
    }
    private fun enableButtonForRollingDices(){
        compositeDisposable.add(
            Completable.fromAction {
                database.getDataAboutRolledCubesDao().insertData(
                        DataAboutRolledCubes(
                            dataRolledCubesId = 1,
                            cubes = Cubes(1, 1, 1, 1, 1, 1),
                            aheadCall = false,
                            isRecyclerFrozen = true,
                            enableButtonForRollingDices = true
                        )
                    )
            }.subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe()
        )
    }
    private fun generateStartingItems(){
        compositeDisposable.add(
            Single.just(ListOfItemsModifier.generateStartingItems())
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe({
                    itemsInRecycler_.value = it
                }){
                    throw it
                }
        )
    }
    //za generiranje pocetnog listica pomocu kojeg testiram kraj igre
    private fun generateStartingTestItems() {
      compositeDisposable.add(
          Single.just(ListOfItemsModifier.generateStartingTestItems())
              .subscribeOn(Schedulers.io())
              .observeOn(AndroidSchedulers.mainThread())
              .subscribe({
                  itemsInRecycler_.value = it
              }){
                  throw it
              }
      )
    }
    private fun generateDiceRolledWithDataFromDatabase(cubesRolled : Cubes) : List<Int>{
        val tempDiceRolledList = mutableListOf<Int>()

        tempDiceRolledList.add(cubesRolled.cubeOne)
        tempDiceRolledList.add(cubesRolled.cubeTwo)
        tempDiceRolledList.add(cubesRolled.cubeThree)
        tempDiceRolledList.add(cubesRolled.cubeFour)
        tempDiceRolledList.add(cubesRolled.cubeFive)
        tempDiceRolledList.add(cubesRolled.cubeSix)

        return tempDiceRolledList
    }
    override fun changeIsPopUpDialogEnabledState(position: Int,clickable : Boolean){
        if(clickable){
            positioOfLastItemClickedTemp = position
            isPopUpForEnteringValuesEnabled_.value = true
            isPopUpForEnteringValuesEnabled_.value = false
        }

    }
    override fun disposeOfObservers(){
        compositeDisposable.dispose()
    }

}